// Design: D11.v6.indicator-sync S1-S7
import assert from 'node:assert/strict';
import * as addons from '../web/js/addons.js';
import {toggleIndicatorSync,reconcileIndicators,indicatorProfile,indicatorBodyPatch} from '../web/js/indicator-state.js';
import {createRuntime} from '../web/js/runtime.js';
const candle=code=>({kind:'candles',enabled:true,visible:true,props:{...addons.defaults('candles',{id:'candles1'}),code,tf:'1m'}});
let body={items:{candles1:candle('005930'),candles2:candle('000660'),ma3:{kind:'ma',enabled:true,visible:true,props:{len:2,color:'#fff',width:1}}},order:['candles1','candles2','ma3'],ui:{selectedItemId:'candles1'},panes:[{id:'main',h:300}],view:{}};
const original=structuredClone(body);
body=toggleIndicatorSync(body,true,addons);
assert.equal(original.items.ma3.props.targetItemId,undefined);
assert.equal(body.items.ma3.props.targetItemId,'candles1');
const peer=body.order.find(id=>body.items[id].props.syncOriginId==='ma3');
assert.ok(peer);assert.equal(body.items[peer].props.targetItemId,'candles2');
assert.deepEqual(toggleIndicatorSync(body,true,addons),body);
body.items.ma3.props.len=3;body=reconcileIndicators(body,addons);
assert.equal(body.items[peer].props.len,3);
body=toggleIndicatorSync(body,false,addons);body.items.ma3.props.len=2;body=reconcileIndicators(body,addons);
assert.equal(body.items[peer].props.len,3);
body.items[peer].props.len=2;
const form={code:'005930',tf:'1m',body};
const bars=value=>[1,2,3].map(time=>({time,open:value,high:value,low:value,close:value,volume:1}));
const data=new Map([['005930|1m',{bars:bars(100),barsHash:'A'}],['000660|1m',{bars:bars(200),barsHash:'B'}]]);
const made=[];const removed=[];
const engine={addSeries(type,opts,pane){const s={type,opts,pane,setData(rows){this.data=rows;},applyOptions(p){Object.assign(this.opts,p);},update(){}};made.push(s);return s;},setSeriesScaleOptions(){},removeSeries(s){removed.push(s);},trimPanes(){}};
const runtime=createRuntime({core:engine,registry:addons});
const ctx={engine,form,bars:data.get('005930|1m').bars,barsHash:'A',dataFor:key=>data.get(key)};
let projection=indicatorProfile(form,addons);
assert.equal(projection.items[peer].props.dataKey,'000660|1m');
let result=runtime.apply(projection,true,ctx,false);
assert.equal(made[2].data[0].value,100);assert.equal(made[3].data[0].value,200);
assert.equal(runtime.apply(projection,true,ctx,false).ops.length,0);
form.body.items.ma3.props.len=3;
result=runtime.apply(indicatorProfile(form,addons),true,ctx,false);
assert.deepEqual(result.ops.map(e=>[e.op,e.id]),[['update','ma3']]);
assert.equal(removed.length,0);
form.body.items.candles2.visible=false;
result=runtime.apply(indicatorProfile(form,addons),true,ctx,false);
assert.deepEqual(new Set(result.ops.map(e=>e.id)),new Set(['candles2',peer]));
body.ui.selectedItemId='candles2';body=toggleIndicatorSync(body,true,addons);
assert.equal(body.items[peer].props.syncOriginId,undefined);
delete body.items.candles2;body.order=body.order.filter(id=>id!=='candles2');
body=reconcileIndicators(body,addons);assert.equal(body.indicatorSync.enabled,false);assert.equal(body.items[peer],undefined);
assert.equal(toggleIndicatorSync({...body,ui:{selectedItemId:null}},true,addons),null);
const previous={items:{ma1:{props:{syncOriginId:'ma2',targetItemId:'candles1'}}},order:['ma1']};
const next={items:{ma1:{props:{targetItemId:'candles1'}}},order:['ma1']};
assert.equal(indicatorBodyPatch(previous,next,'DELETE').items.ma1.props.syncOriginId,'DELETE');
assert.equal(previous.items.ma1.props.syncOriginId,'ma2');
console.log('[PASS] D11 indicator sync per-symbol data, propagation, OFF isolation and locality');
